### ISSUE TITLE
Hi there 

### ISSUE THREAD

**Issue by aquapi** [ragokan/bunicorn-benchmark#1]
:)

Why you removed Stric ;-;

**Comment by aquapi** [comment]
That performance is really good actually.

**Comment by aquapi** [comment]
![image](https://github.com/ragokan/bunicorn-benchmark/assets/87530663/353bd0b8-425e-4e05-aa40-32b9358ae654)
Here's my latest result.

Your routing algorithm has O(n) check btw, which is not what you should do

Normally static route should be O(1), and wildcard depends but usually it is O(depth), which is the depth of the radix tree

**Comment by ragokan** [comment]
I will add Stric, it is definitely so fast. For performance I don't know what is wrong with O(1), you can, of course, modify the code to contribute. Thanks a lot for suggestion!

**Comment by aquapi** [comment]
I already built a router that I use for stric tho
See aquapi/wint

**Comment by ragokan** [comment]
Thank you, will do!
